teleport-delay: 5
#-1 = Infinity Effect
nightvision-duration: 999999 # مدت زمان فعال بودن افکت نایت ویژن (در تیک‌ها)
#Level Effect
nightvision-amplifier: 0
messages:
  creative: "&x&E&3&3&4&1&4ℹ &eʏᴏᴜʀ ɢᴀᴍᴇ ᴍᴏᴅᴇ ʜᴀꜱ ʙᴇᴇɴ ᴄʜᴀɴɢᴇᴅ ᴛᴏ &cᴄʀᴇᴀᴛɪᴠᴇ."
  adventure: "&x&E&3&3&4&1&4ℹ &eʏᴏᴜʀ ɢᴀᴍᴇ ᴍᴏᴅᴇ ʜᴀꜱ ʙᴇᴇɴ ᴄʜᴀɴɢᴇᴅ ᴛᴏ &cᴀᴅᴠᴇɴᴛᴜʀᴇ."
  survival: "&x&E&3&3&4&1&4ℹ &eʏᴏᴜʀ ɢᴀᴍᴇ ᴍᴏᴅᴇ ʜᴀꜱ ʙᴇᴇɴ ᴄʜᴀɴɢᴇᴅ ᴛᴏ &cꜱᴜʀᴠɪᴠᴀʟ."
  spectator: "&x&E&3&3&4&1&4ℹ &eʏᴏᴜʀ ɢᴀᴍᴇ ᴍᴏᴅᴇ ʜᴀꜱ ʙᴇᴇɴ ᴄʜᴀɴɢᴇᴅ ᴛᴏ &cꜱᴘᴇᴄᴛᴀᴛᴏʀ."
  not-a-player: "&x&E&3&3&4&1&4🚫 &fᴛʜɪꜱ ᴄᴏᴍᴍᴀɴᴅ ᴄᴀɴ ᴏɴʟʏ ʙᴇ ᴜꜱᴇᴅ ʙʏ ᴘʟᴀʏᴇʀꜱ."
  no-argument: "&x&E&3&3&4&1&4❓ &fPlease specify an argument: &6hand &for &6all&f."
  invalid-argument: "&x&E&3&3&4&1&4🚫 &fᴘʟᴇᴀꜱᴇ ꜱᴘᴇᴄɪꜰʏ ᴀɴ ᴀʀɢᴜᴍᴇɴᴛ: &6ʜᴀɴᴅ &ꜰᴏʀ &6ᴀʟʟ&f."
  repaired-hand: "&x&E&3&3&4&1&4🔧 &fʏᴏᴜʀ ɪᴛᴇᴍ ɪɴ ʜᴀɴᴅ &e({item})&f ʜᴀꜱ ʙᴇᴇɴ ʀᴇᴘᴀɪʀᴇᴅ."
  repaired-all: "&x&E&3&3&4&1&4🔧 &fᴀʟʟ ɪᴛᴇᴍꜱ ɪɴ ʏᴏᴜʀ ɪɴᴠᴇɴᴛᴏʀʏ ʜᴀᴠᴇ ʙᴇᴇɴ ʀᴇᴘᴀɪʀᴇᴅ."
  spawn-set: "&x&E&3&3&4&1&4ℹ &aꜱᴘᴀᴡɴ ʟᴏᴄᴀᴛɪᴏɴ ꜱᴇᴛ!"
  spawn-not-set: "&x&E&3&3&4&1&4ℹ ꜱᴘᴀᴡɴ ʟᴏᴄᴀᴛɪᴏɴ ʜᴀꜱ ɴᴏᴛ ʙᴇᴇɴ ꜱᴇᴛ ʏᴇᴛ!"
  teleporting: "&x&E&3&3&4&1&4ℹ &eᴛᴇʟᴇᴘᴏʀᴛɪɴɢ ɪɴ %d ꜱᴇᴄᴏɴᴅꜱ..."
  teleport-cancelled: "&x&E&3&3&4&1&4ℹ &cᴛᴇʟᴇᴘᴏʀᴛ ᴛᴏ ꜱᴘᴀᴡɴ ᴄᴀɴᴄᴇʟʟᴇᴅ ᴅᴜᴇ ᴛᴏ ᴍᴏᴠᴇᴍᴇɴᴛ."
  teleported: "&x&E&3&3&4&1&4ℹ &aᴛᴇʟᴇᴘᴏʀᴛᴇᴅ ᴛᴏ ꜱᴘᴀᴡɴ!"
  no-permission: "&x&E&3&3&4&1&4ℹ &cʏᴏᴜ ᴅᴏ ɴᴏᴛ ʜᴀᴠᴇ ᴘᴇʀᴍɪꜱꜱɪᴏɴ ᴛᴏ ᴜꜱᴇ ᴛʜɪꜱ ᴄᴏᴍᴍᴀɴᴅ."
  target: "&x&E&3&3&4&1&4ℹ &aʏᴏᴜ ᴄʜᴀɴɢᴇᴅ &b%player%'ꜱ &aɢᴀᴍᴇ ᴍᴏᴅᴇ ᴛᴏ &b%mode%."
  player-not-found: "&cPlayer not found."
  flight-enabled: "&aFlight enabled for {player}."
  flight-disabled: "&cFlight disabled for {player}."
  usage: "&cUsage: /fly [playername] enable/disable"
  invalid_argument: "&cInvalid argument. Use 'enable' or 'disable'."
  nightvision-activated: "&3NightVision &aActivated"
  nightvision-disabled: "&3NightVision &cDisabled"